"""empty message

Revision ID: 478d8e40bb4d
Revises: 79de38cc7ace
Create Date: 2025-04-10 01:01:52.370295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478d8e40bb4d'
down_revision = '79de38cc7ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=25), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('last_name')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
