"""empty message

Revision ID: b0027ddd19a5
Revises: d94a8674bd40
Create Date: 2025-04-10 01:34:23.878948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0027ddd19a5'
down_revision = 'd94a8674bd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_comment_text_key', type_='unique')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('media_type_key', type_='unique')
        batch_op.drop_constraint('media_url_key', type_='unique')
        batch_op.drop_constraint('media_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('media_post_id_fkey', 'post', ['post_id'], ['id'])
        batch_op.create_unique_constraint('media_url_key', ['url'])
        batch_op.create_unique_constraint('media_type_key', ['type'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_unique_constraint('comment_comment_text_key', ['comment_text'])

    # ### end Alembic commands ###
